site_name: stac-hash
site_description: Configurable, sortable spatio-temporal hashes, good for STAC items
site_url: https://gadomski.github.io/stac-hash
repo_url: https://github.com/gadomski/stac-hash
repo_name: gadomski/stac-hash
strict: true

exclude_docs: |
  superpowers/

nav:
  - Home: index.md
  - Usage: usage.md
  - Tutorials:
      - Create Hash GeoParquet: tutorials/create-hash-geoparquet.ipynb
  - STAC Extension: stac-extension.md
  - API: api.md

theme:
  name: material
  logo: img/stac-hash.png
  favicon: img/stac-hash.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - toc.integrate
  palette:
    scheme: stac
    primary: custom

extra:
  version:
    provider: mike

plugins:
  - search
  - mike
  - mkdocs-jupyter:
      execute: false
      include_source: true
  - social:
      cards_layout_options:
        color: rgb(26, 78, 99)
        background_color: rgb(228, 246, 251)
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            allow_inspection: false
            docstring_section_style: list
            docstring_style: google
            line_length: 80
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_toc: true
            signature_crossrefs: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
