name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: docs
  cancel-in-progress: false

jobs:
  docs:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - name: Sync
        run: uv sync --group docs
      - name: Deploy
        env:
          GIT_COMMITTER_NAME: ci-bot
          GIT_COMMITTER_EMAIL: ci-bot@example.com
        run: |
          version=$(grep -m1 '^version = ' Cargo.toml | cut -d'"' -f2)
          uv run mike deploy --push --update-aliases "$version" latest
          uv run mike set-default --push latest
